#!/bin/bash

read -p "Enter commit message: " commit_msg

# Ignore files with the tilde symbol
#echo "*~" >> .gitignore

git add "$commit_msg"
#git add .gitignore
git commit -am "$commit_msg"
git push
